name: moviesto
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^3.2.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_core: ^1.13.1
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.3.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  freezed_annotation: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.1.0
  auto_route_generator: ^3.2.3
  injectable_generator: ^1.5.3
  build_runner: ^2.1.7
  freezed: ^1.1.1
flutter:
  uses-material-design: true
  assets:
    - assets/